import packageJsonTemplateText from '../../package.json?raw';
import packageLockTemplateText from '../../package-lock.json?raw';
import type { ComposerManifest } from '@/composer/composer.types';
import type { ExportProject, ExportProjectFile } from '@/export/export.types';
import { createStoredZip } from '@/export/export.zip';

type PackageTemplate = {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  engines?: Record<string, string>;
};

type PackageLockTemplate = {
  name?: string;
  version?: string;
  packages?: Record<string, { name?: string; version?: string }>;
};

const packageTemplate = JSON.parse(packageJsonTemplateText) as PackageTemplate;

function projectPackageName(slug: string) {
  return slug.replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || 'webblueprint-app';
}

function assertExportableManifest(manifest: ComposerManifest) {
  if (!manifest.application.name.trim()) {
    throw new Error('Cannot export an application without a name.');
  }

  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(manifest.application.slug)) {
    throw new Error('Cannot export an application with an invalid slug.');
  }

  const pageIds = new Set(manifest.pages.map((page) => page.id));
  if (manifest.navigation.items.some((item) => !pageIds.has(item.pageId))) {
    throw new Error('Navigation references a page that is not included in the export.');
  }
}

function createPackageJson(manifest: ComposerManifest) {
  return `${JSON.stringify(
    {
      name: projectPackageName(manifest.application.slug),
      private: true,
      version: '0.1.0',
      type: 'module',
      engines: packageTemplate.engines,
      scripts: {
        dev: 'vite',
        build: 'tsc --noEmit && vite build',
        preview: 'vite preview',
      },
      dependencies: packageTemplate.dependencies,
      devDependencies: packageTemplate.devDependencies,
    },
    null,
    2,
  )}\n`;
}

function createPackageLock(manifest: ComposerManifest) {
  const packageName = projectPackageName(manifest.application.slug);
  const lock = JSON.parse(packageLockTemplateText) as PackageLockTemplate;
  lock.name = packageName;
  lock.version = '0.1.0';

  const rootPackage = lock.packages?.[''];
  if (rootPackage) {
    rootPackage.name = packageName;
    rootPackage.version = '0.1.0';
  }

  return `${JSON.stringify(lock, null, 2)}\n`;
}

function createGeneratedApplication(manifest: ComposerManifest) {
  return `export const application = ${JSON.stringify(manifest, null, 2)} as const;\n`;
}

const appSource = `import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { application } from './generated/application';

export function App() {
  const pages = application.pages;
  const [activePageId, setActivePageId] = useState<string | null>(pages[0]?.id ?? null);
  const [collapsed, setCollapsed] = useState(false);
  const activePage = useMemo(() => pages.find((page) => page.id === activePageId) ?? pages[0], [activePageId, pages]);
  const shellVariant = String(application.navigation.shellVariant);
  const dark = shellVariant === 'vertical-dark-menu';
  const collapsible = shellVariant === 'collapsible-menu';
  const shellStyle = { '--accent': application.branding.accentColor } as CSSProperties;

  return (
    <div className={\`app-shell \${dark ? 'is-dark' : ''} \${collapsed ? 'is-collapsed' : ''}\`} style={shellStyle}>
      <aside className="sidebar">
        <div className="brand-row">
          {application.branding.logoUrl ? <img className="brand-logo" src={application.branding.logoUrl} alt="" /> : <div className="brand-mark" />}
          {!collapsed && <div className="brand-copy"><strong>{application.application.name}</strong><span>Generated by WebBlueprint</span></div>}
        </div>
        <nav className="nav-list">
          {application.navigation.items.length > 0 ? application.navigation.items.map((item, index) => (
            <button className={item.pageId === activePage?.id ? 'nav-item active' : 'nav-item'} key={item.pageId} onClick={() => setActivePageId(item.pageId)} type="button">
              <span className="nav-index">{String(index + 1).padStart(2, '0')}</span>
              {!collapsed && <span>{item.label}</span>}
            </button>
          )) : !collapsed ? <p className="empty-nav">No pages selected.</p> : null}
        </nav>
      </aside>

      <div className="workspace">
        <header className="topbar">
          {collapsible && <button className="secondary-button" onClick={() => setCollapsed((value) => !value)} type="button">{collapsed ? 'Expand' : 'Collapse'}</button>}
          <div><strong>{activePage?.label ?? application.application.name}</strong><span>{application.application.description || 'Generated application'}</span></div>
        </header>
        <main className="content">
          <section className="hero-card">
            <p className="eyebrow">Generated application</p>
            <h1>{activePage?.label ?? application.application.name}</h1>
            <p>{activePage ? \`Route /\${activePage.path}\` : 'Choose pages in WebBlueprint to generate navigation.'}</p>
          </section>
          <section className="feature-grid">
            {application.features.length > 0 ? application.features.map((feature) => (
              <article className="feature-card" key={feature.id}>
                <span>{feature.id}</span>
                <strong>{feature.label}</strong>
                <p>This capability was selected in App Composer and carried into the export manifest.</p>
              </article>
            )) : <article className="feature-card"><strong>Blank surface</strong><p>Add features in App Composer before exporting when the application needs them.</p></article>}
          </section>
        </main>
      </div>
    </div>
  );
}
`;

const mainSource = `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import './styles.css';

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
`;

const styleSource = `:root { font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #0f172a; background: #f8fafc; }
* { box-sizing: border-box; }
body { margin: 0; min-width: 320px; min-height: 100vh; }
button { font: inherit; }
.app-shell { --sidebar: 240px; min-height: 100vh; display: grid; grid-template-columns: var(--sidebar) minmax(0, 1fr); background: #f8fafc; }
.app-shell.is-collapsed { --sidebar: 72px; }
.sidebar { position: sticky; top: 0; height: 100vh; overflow: auto; border-right: 1px solid #e2e8f0; background: white; color: #334155; padding: 14px 12px; }
.is-dark .sidebar { background: #0f172a; color: #e2e8f0; border-color: #1e293b; }
.brand-row { min-height: 48px; display: flex; align-items: center; gap: 10px; padding: 0 6px 14px; border-bottom: 1px solid #e2e8f0; }
.is-dark .brand-row { border-color: #334155; }
.brand-logo, .brand-mark { width: 34px; height: 34px; flex: 0 0 auto; border-radius: 10px; object-fit: contain; background: var(--accent); }
.brand-copy { min-width: 0; display: grid; gap: 2px; }
.brand-copy strong { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.brand-copy span, .topbar span { color: #64748b; font-size: 11px; }
.nav-list { display: grid; gap: 6px; padding-top: 12px; }
.nav-item { width: 100%; min-height: 40px; display: flex; align-items: center; gap: 10px; border: 0; border-radius: 10px; background: transparent; color: inherit; cursor: pointer; text-align: left; padding: 8px 10px; }
.nav-item:hover { background: #f1f5f9; }
.is-dark .nav-item:hover { background: #1e293b; }
.nav-item.active { background: color-mix(in srgb, var(--accent) 11%, white); color: var(--accent); font-weight: 700; }
.is-dark .nav-item.active { background: color-mix(in srgb, var(--accent) 22%, #0f172a); color: #bfdbfe; }
.nav-index { width: 24px; height: 24px; display: grid; place-items: center; flex: 0 0 auto; border-radius: 7px; background: #f1f5f9; font-size: 10px; }
.is-dark .nav-index { background: #334155; }
.empty-nav { padding: 8px; color: #64748b; font-size: 12px; }
.workspace { min-width: 0; }
.topbar { position: sticky; top: 0; z-index: 2; min-height: 62px; display: flex; align-items: center; gap: 12px; padding: 10px 22px; border-bottom: 1px solid #e2e8f0; background: rgba(255,255,255,.94); backdrop-filter: blur(10px); }
.topbar > div { min-width: 0; display: grid; gap: 2px; }
.topbar strong, .topbar span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.secondary-button { border: 1px solid #e2e8f0; border-radius: 9px; background: white; padding: 7px 10px; color: #475569; cursor: pointer; font-size: 12px; font-weight: 700; }
.content { max-width: 1200px; margin: 0 auto; padding: 24px; }
.hero-card, .feature-card { border: 1px solid #e2e8f0; background: white; border-radius: 16px; box-shadow: 0 1px 2px rgba(15,23,42,.04); }
.hero-card { padding: 24px; }
.eyebrow { margin: 0; color: var(--accent); font-size: 11px; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; }
h1 { margin: 7px 0 0; font-size: clamp(28px, 5vw, 44px); letter-spacing: -.04em; }
.hero-card > p:last-child { max-width: 700px; margin: 10px 0 0; color: #64748b; line-height: 1.6; }
.feature-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 14px; margin-top: 16px; }
.feature-card { padding: 18px; }
.feature-card span { display: block; color: var(--accent); font: 700 10px/1.4 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; }
.feature-card strong { display: block; margin-top: 8px; }
.feature-card p { margin: 8px 0 0; color: #64748b; font-size: 13px; line-height: 1.55; }
@media (max-width: 900px) { .feature-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }
@media (max-width: 700px) { .app-shell, .app-shell.is-collapsed { --sidebar: 76px; } .brand-copy, .nav-item > span:last-child, .empty-nav { display: none; } .nav-item { justify-content: center; padding-inline: 6px; } .topbar { padding-inline: 14px; } .content { padding: 16px 14px; } .feature-grid { grid-template-columns: 1fr; } }
`;

const indexHtml = `<!doctype html>
<html lang="en">
  <head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="color-scheme" content="light" /><title>WebBlueprint Export</title></head>
  <body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>
</html>
`;

const viteConfig = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({ plugins: [react()] });
`;

const tsconfig = `{
  "compilerOptions": {
    "target": "ES2023",
    "useDefineForClassFields": true,
    "lib": ["ES2023", "DOM", "DOM.Iterable"],
    "skipLibCheck": true,
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "noEmit": true,
    "jsx": "react-jsx",
    "types": ["vite/client"]
  },
  "include": ["src", "vite.config.ts"]
}
`;

function createReadme(manifest: ComposerManifest) {
  return `# ${manifest.application.name}\n\nGenerated by WebBlueprint Export Engine v0.\n\n## Run\n\n\`\`\`bash\nnpm ci\nnpm run dev\n\`\`\`\n\n## Verify\n\n\`\`\`bash\nnpm run build\n\`\`\`\n\nThe generation source is preserved in \`webblueprint.json\`.\n`;
}

export function buildReactExportProject(manifest: ComposerManifest): ExportProject {
  assertExportableManifest(manifest);

  const files: ExportProjectFile[] = [
    { path: '.gitignore', content: 'node_modules\ndist\n.DS_Store\n' },
    { path: 'README.md', content: createReadme(manifest) },
    { path: 'index.html', content: indexHtml },
    { path: 'package-lock.json', content: createPackageLock(manifest) },
    { path: 'package.json', content: createPackageJson(manifest) },
    { path: 'src/App.tsx', content: appSource },
    { path: 'src/generated/application.ts', content: createGeneratedApplication(manifest) },
    { path: 'src/main.tsx', content: mainSource },
    { path: 'src/styles.css', content: styleSource },
    { path: 'tsconfig.json', content: tsconfig },
    { path: 'vite.config.ts', content: viteConfig },
    { path: 'webblueprint.json', content: `${JSON.stringify(manifest, null, 2)}\n` },
  ];

  return { rootName: projectPackageName(manifest.application.slug), files };
}

export function buildReactExportZip(manifest: ComposerManifest) {
  const project = buildReactExportProject(manifest);
  return { fileName: `${project.rootName}.zip`, bytes: createStoredZip(project.files) };
}

export function downloadReactExportZip(manifest: ComposerManifest) {
  const { bytes, fileName } = buildReactExportZip(manifest);
  const arrayBuffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer;
  const blob = new Blob([arrayBuffer], { type: 'application/zip' });
  const objectUrl = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = objectUrl;
  link.download = fileName;
  link.click();
  URL.revokeObjectURL(objectUrl);
}
