import type { LockScreenViewDto } from '@/features/authentication/lock-screen/application/dtos/lockScreen.dto';
type R = Record<string, unknown>;
const record = (v: unknown, f: string): R => { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new Error(`Invalid ${f}`); return v as R; };
const str = (v: unknown, f: string) => { if (typeof v !== 'string' || !v.trim()) throw new Error(`Invalid ${f}`); return v; };
const nullable = (v: unknown, f: string) => v === null ? null : str(v, f);
export function mapLockScreenViewDto(value: unknown): LockScreenViewDto {
  const root = record(value, 'lock-screen view'); const hero = record(root.hero, 'hero'); const form = record(root.form, 'form'); const identity = record(form.identity, 'form.identity'); const password = record(form.password, 'form.password'); const back = record(form.backToSignIn, 'form.backToSignIn'); const validation = record(form.validation, 'form.validation'); const feedback = record(form.feedback, 'form.feedback'); const legal = record(root.legal, 'legal');
  const branding = record(root.branding, 'branding'); const highlights = hero.highlights; if (!Array.isArray(highlights) || !highlights.length) throw new Error('Invalid hero.highlights');
  return { branding: { mark: str(branding.mark,'branding.mark'), name: str(branding.name,'branding.name'), logoUrl: nullable(branding.logoUrl,'branding.logoUrl'), contextLabel: str(branding.contextLabel,'branding.contextLabel') }, hero: { eyebrow: str(hero.eyebrow,'hero.eyebrow'), title: str(hero.title,'hero.title'), description: str(hero.description,'hero.description'), highlights: highlights.map((v,i) => { const h=record(v,`hero.highlights[${i}]`); return { id:str(h.id,'highlight.id'), title:str(h.title,'highlight.title'), description:str(h.description,'highlight.description') }; }) }, form: { eyebrow:str(form.eyebrow,'form.eyebrow'), title:str(form.title,'form.title'), description:str(form.description,'form.description'), identity:{ name:str(identity.name,'identity.name'), detail:str(identity.detail,'identity.detail'), initials:str(identity.initials,'identity.initials') }, password:{ label:str(password.label,'password.label'), placeholder:str(password.placeholder,'password.placeholder'), autocomplete:str(password.autocomplete,'password.autocomplete') }, passwordHint:str(form.passwordHint,'form.passwordHint'), submitLabel:str(form.submitLabel,'form.submitLabel'), submittingLabel:str(form.submittingLabel,'form.submittingLabel'), demoNotice:str(form.demoNotice,'form.demoNotice'), backToSignIn:{ prompt:str(back.prompt,'back.prompt'), label:str(back.label,'back.label'), href:str(back.href,'back.href') }, validation:{ passwordRequired:str(validation.passwordRequired,'validation.passwordRequired') }, feedback:{ successTitle:str(feedback.successTitle,'feedback.successTitle'), successMessage:str(feedback.successMessage,'feedback.successMessage'), invalidPassword:str(feedback.invalidPassword,'feedback.invalidPassword'), unavailable:str(feedback.unavailable,'feedback.unavailable') } }, legal:{ privacyLabel:str(legal.privacyLabel,'legal.privacyLabel'), privacyHref:str(legal.privacyHref,'legal.privacyHref'), termsLabel:str(legal.termsLabel,'legal.termsLabel'), termsHref:str(legal.termsHref,'legal.termsHref') } };
}
