import { useState } from 'react';
import { AppIcon, type AppIconName } from '@/components/AppIcon';
import { SurfaceCard } from '@/components/layout/SurfaceCard';
import { PageShell } from '@/shell/PageShell';

export type ComponentShowcaseKind = 'accordion' | 'cards' | 'carousel' | 'drag-drop' | 'lightbox' | 'lists' | 'modal-dialog' | 'notifications' | 'pricing' | 'tabs' | 'timeline';

interface ComponentShowcasePageProps {
  kind: ComponentShowcaseKind;
  title: string;
  description: string;
}

function DemoHeader({ icon, title, description }: { icon: AppIconName; title: string; description: string }) {
  return <div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-md bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]"><AppIcon className="size-[18px]" name={icon} /></div><div><h2 className="text-[13px] font-semibold text-slate-900">{title}</h2><p className="mt-1 text-[11px] leading-4 text-slate-500">{description}</p></div></div>;
}

function ComponentDemo({ kind }: { kind: ComponentShowcaseKind }) {
  const [activeTab, setActiveTab] = useState('Resumen');
  const [open, setOpen] = useState(false);
  if (kind === 'accordion') return <div className="space-y-2">{['¿Qué incluye este componente?', '¿Es accesible?', '¿Admite contenido dinámico?'].map((item, index) => <details key={item} className="rounded-md border border-slate-100 bg-slate-50/60 p-3" open={index === 0}><summary className="cursor-pointer text-[11px] font-semibold text-slate-800">{item}</summary><p className="mt-2 text-[11px] leading-4 text-slate-500">Contenido colapsable con una jerarquía clara y foco nativo del navegador.</p></details>)}</div>;
  if (kind === 'cards') return <div className="grid gap-2 sm:grid-cols-3">{['Proyecto Aurora', 'Sistema Atlas', 'Portal Nova'].map((item, index) => <div key={item} className="rounded-md border border-slate-200 p-3"><p className="text-[12px] font-semibold text-slate-800">{item}</p><p className="mt-1 text-[11px] text-slate-500">{index + 3} colaboradores activos</p><span className="mt-3 inline-flex rounded-full bg-[var(--theme-primary-soft)] px-2 py-1 text-[10px] font-semibold text-[var(--theme-primary)]">Activo</span></div>)}</div>;
  if (kind === 'carousel') return <div className="rounded-md border border-slate-100 bg-slate-50/70 p-6 text-center"><p className="text-lg font-semibold text-slate-800">Slide 01</p><p className="mt-1 text-[11px] text-slate-500">Contenido adaptable para galerías y destacados.</p><div className="mt-4 flex justify-center gap-1"><span className="size-1.5 rounded-full bg-[var(--theme-primary)]" /><span className="size-1.5 rounded-full bg-slate-300" /><span className="size-1.5 rounded-full bg-slate-300" /></div></div>;
  if (kind === 'drag-drop') return <div className="grid gap-2 sm:grid-cols-2"><div className="rounded-md border-2 border-dashed border-[var(--theme-primary-border)] bg-[var(--theme-primary-soft)] p-5 text-center"><AppIcon className="mx-auto size-5 text-[var(--theme-primary)]" name="layers" /><p className="mt-2 text-[11px] font-semibold text-slate-800">Arrastra aquí</p><p className="mt-1 text-[10px] text-slate-500">Zona de destino</p></div><div className="rounded-md border border-slate-200 p-5 text-center"><p className="text-[11px] font-semibold text-slate-800">Elemento movible</p><p className="mt-1 text-[10px] text-slate-500">Estado listo</p></div></div>;
  if (kind === 'lightbox') return <div className="grid place-items-center rounded-md bg-slate-900 p-8 text-center"><div className="grid size-12 place-items-center rounded-full bg-white/10 text-white"><AppIcon className="size-6" name="search" /></div><p className="mt-3 text-[11px] font-semibold text-white">Vista previa de imagen</p><p className="mt-1 text-[10px] text-slate-300">La capa de lightbox mantiene el foco en el contenido.</p></div>;
  if (kind === 'lists') return <div className="divide-y divide-slate-100 rounded-md border border-slate-100">{['Diseño visual', 'Contenido', 'Accesibilidad'].map((item, index) => <div key={item} className="flex items-center justify-between px-3 py-3"><span className="text-[11px] font-medium text-slate-700">{item}</span><span className="text-[10px] text-slate-400">0{index + 1}</span></div>)}</div>;
  if (kind === 'modal-dialog') return <div className="text-center"><button className="rounded-md bg-[var(--theme-primary)] px-3 py-2 text-[11px] font-semibold text-white" onClick={() => setOpen(true)} type="button">Abrir diálogo</button>{open ? <div className="mt-4 rounded-md border border-[var(--theme-primary-border)] bg-[var(--theme-primary-soft)] p-4 text-left"><div className="flex items-center justify-between"><p className="text-[12px] font-semibold text-slate-800">Diálogo activo</p><button className="text-[11px] font-semibold text-[var(--theme-primary)]" onClick={() => setOpen(false)} type="button">Cerrar</button></div><p className="mt-2 text-[11px] text-slate-600">El estado se controla desde la interacción de la vista.</p></div> : null}</div>;
  if (kind === 'notifications') return <div className="space-y-2"><div className="flex items-start gap-3 rounded-md border border-emerald-100 bg-emerald-50/70 p-3"><AppIcon className="mt-0.5 size-4 text-emerald-700" name="bell" /><div><p className="text-[11px] font-semibold text-emerald-800">Cambios guardados</p><p className="mt-1 text-[10px] text-emerald-700">La notificación comunica resultado y contexto.</p></div></div><div className="flex items-start gap-3 rounded-md border border-amber-100 bg-amber-50/70 p-3"><AppIcon className="mt-0.5 size-4 text-amber-700" name="bell" /><div><p className="text-[11px] font-semibold text-amber-800">Revisión pendiente</p><p className="mt-1 text-[10px] text-amber-700">El estado de atención queda visible.</p></div></div></div>;
  if (kind === 'pricing') return <div className="grid gap-2 sm:grid-cols-3">{[['Básico', '$0'], ['Equipo', '$24'], ['Escala', '$59']].map(([name, price], index) => <div key={name} className={`rounded-md border p-4 ${index === 1 ? 'border-[var(--theme-primary)] shadow-sm' : 'border-slate-200'}`}><p className="text-[12px] font-semibold text-slate-800">{name}</p><p className="mt-2 text-xl font-semibold text-slate-900">{price}<span className="text-[10px] font-normal text-slate-400">/mes</span></p><button className="mt-4 w-full rounded-md border border-slate-200 px-2 py-2 text-[10px] font-semibold text-slate-700" type="button">Elegir plan</button></div>)}</div>;
  if (kind === 'tabs') return <div><div className="flex gap-1 border-b border-slate-200">{['Resumen', 'Detalles', 'Actividad'].map((tab) => <button key={tab} className={`border-b-2 px-3 py-2 text-[11px] font-semibold ${activeTab === tab ? 'border-[var(--theme-primary)] text-[var(--theme-primary)]' : 'border-transparent text-slate-400'}`} onClick={() => setActiveTab(tab)} type="button">{tab}</button>)}</div><p className="pt-4 text-[11px] text-slate-500">Contenido de la pestaña <strong>{activeTab}</strong>.</p></div>;
  return <div className="relative space-y-4 pl-5 before:absolute before:bottom-0 before:left-1.5 before:top-0 before:w-px before:bg-slate-200">{['Solicitud creada', 'Revisión completada', 'Entrega programada'].map((item, index) => <div key={item} className="relative"><span className="absolute -left-[19px] top-0.5 size-2.5 rounded-full border-2 border-white bg-[var(--theme-primary)] shadow" /><p className="text-[11px] font-semibold text-slate-800">{item}</p><p className="mt-1 text-[10px] text-slate-500">Paso {index + 1} · actualizado recientemente</p></div>)}</div>;
}

export function ComponentShowcasePage({ kind, title, description }: ComponentShowcasePageProps) {
  return <PageShell breadcrumbs={[{ label: 'Componentes' }, { label: title }]} description={description} title={title}><SurfaceCard><DemoHeader description="Ejemplo interactivo sobre los tokens activos del Blueprint." icon="components" title={title} /><div className="mt-5"><ComponentDemo kind={kind} /></div></SurfaceCard><SurfaceCard className="mt-3"><DemoHeader description="Primitivas relacionadas que pueden combinarse con esta vista." icon="layers" title="Composición" /><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-md border border-slate-100 p-3"><p className="text-[11px] font-semibold text-slate-800">Estados</p><p className="mt-1 text-[10px] text-slate-500">Carga, éxito, vacío y error.</p></div><div className="rounded-md border border-slate-100 p-3"><p className="text-[11px] font-semibold text-slate-800">Accesibilidad</p><p className="mt-1 text-[10px] text-slate-500">Foco y semántica visibles.</p></div><div className="rounded-md border border-slate-100 p-3"><p className="text-[11px] font-semibold text-slate-800">Tema</p><p className="mt-1 text-[10px] text-slate-500">Sin colores de marca hardcodeados.</p></div></div></SurfaceCard></PageShell>;
}
