import type { ProjectPresetDefinition } from '@/composer/project.types';

export const projectPresets: readonly ProjectPresetDefinition[] = [
  {
    id: 'blank',
    name: 'Aplicación vacía',
    description: 'Empieza sin vistas seleccionadas y construye la navegación desde cero.',
    viewPaths: [],
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Base comercial con dashboard, catálogo, tienda, clientes, facturas y seguimiento.',
    viewPaths: [
      '/dashboard',
      '/applications/ecommerce/products',
      '/applications/ecommerce/shop',
      '/applications/ecommerce/product',
      '/applications/ecommerce/editor',
      '/applications/contacts',
      '/applications/invoices/list',
      '/applications/invoices/preview',
      '/applications/tasks',
      '/charts',
    ],
  },
  {
    id: 'crm',
    name: 'CRM',
    description: 'Base orientada a relación con clientes, comunicación, tareas y seguimiento visual.',
    viewPaths: [
      '/dashboard',
      '/applications/contacts',
      '/applications/chat',
      '/applications/mailbox',
      '/applications/notes',
      '/applications/kanban',
      '/applications/tasks',
      '/charts',
      '/user/profile',
    ],
  },
  {
    id: 'admin-erp',
    name: 'ERP administrativo',
    description: 'Base administrativa con facturación, seguimiento, métricas y configuración.',
    viewPaths: [
      '/dashboard',
      '/applications/contacts',
      '/applications/invoices/list',
      '/applications/invoices/editor',
      '/applications/invoices/preview',
      '/applications/notes',
      '/applications/tasks',
      '/charts',
      '/widgets',
      '/user/account-settings',
    ],
  },
  {
    id: 'content',
    name: 'Contenido / Blog',
    description: 'Base editorial con listado, cuadrícula, artículo, editor y utilidades de publicación.',
    viewPaths: [
      '/dashboard',
      '/applications/blog/list',
      '/applications/blog/grid',
      '/applications/blog/post',
      '/applications/blog/editor',
      '/applications/notes',
      '/applications/tasks',
    ],
  },
  {
    id: 'fixphone',
    name: 'FixPhone',
    description: 'MVP web para operación, inventario de celulares/repuestos y tienda online, usando solo superficies reales reutilizables.',
    themeColorId: 'blue',
    viewPaths: [
      '/apps/inventory/dashboard',
      '/apps/inventory/devices',
      '/apps/inventory/devices/new',
      '/apps/inventory/devices/evaluation',
      '/applications/management/inventory',
      '/applications/management/customers',
      '/applications/management/orders',
      '/admin/master-data/brands',
      '/admin/master-data/device-models',
      '/admin/master-data/categories',
      '/admin/master-data/colors',
      '/admin/master-data/storage-capacities',
      '/admin/master-data/ram-capacities',
      '/admin/master-data/conditions',
      '/admin/master-data/spare-part-types',
      '/store',
      '/store/products',
      '/store/spare-parts',
      '/store/used-phones',
      '/store/brands',
      '/store/products/iphone-13-display-oled',
      '/store/cart',
      '/store/favorites',
      '/store/checkout',
      '/store/shipping',
      '/store/contact',
      '/store/warranty',
      '/store/account/sign-in',
      '/store/account/register',
      '/user/profile',
      '/user/account-settings',
      '/authentication/sign-in',
      '/authentication/password-reset',
      '/authentication/two-factor',
    ],
    viewPresentation: {
      '/apps/inventory/dashboard': { label: 'Panel operativo', section: 'Operación' },
      '/apps/inventory/devices': { label: 'Equipos', section: 'Operación' },
      '/apps/inventory/devices/new': { label: 'Registrar equipo', section: 'Operación' },
      '/apps/inventory/devices/evaluation': { label: 'Evaluación', section: 'Operación' },
      '/applications/management/inventory': { label: 'Inventario', section: 'Inventario' },
      '/applications/management/customers': { label: 'Clientes', section: 'Comercial' },
      '/applications/management/orders': { label: 'Pedidos', section: 'Comercial' },
      '/admin/master-data/brands': { label: 'Marcas', section: 'Catálogo maestro' },
      '/admin/master-data/device-models': { label: 'Modelos', section: 'Catálogo maestro' },
      '/admin/master-data/categories': { label: 'Categorías', section: 'Catálogo maestro' },
      '/admin/master-data/colors': { label: 'Colores', section: 'Catálogo maestro' },
      '/admin/master-data/storage-capacities': { label: 'Almacenamientos', section: 'Catálogo maestro' },
      '/admin/master-data/ram-capacities': { label: 'RAM', section: 'Catálogo maestro' },
      '/admin/master-data/conditions': { label: 'Condiciones', section: 'Catálogo maestro' },
      '/admin/master-data/spare-part-types': { label: 'Tipos de repuesto', section: 'Catálogo maestro' },
      '/store': { label: 'Tienda', section: 'Tienda online' },
      '/store/products': { label: 'Productos', section: 'Tienda online' },
      '/store/spare-parts': { label: 'Repuestos', section: 'Tienda online' },
      '/store/used-phones': { label: 'Celulares usados', section: 'Tienda online' },
      '/store/brands': { label: 'Marcas', section: 'Tienda online' },
      '/store/products/iphone-13-display-oled': { label: 'Detalle de producto', section: 'Tienda online' },
      '/store/cart': { label: 'Carrito', section: 'Tienda online' },
      '/store/favorites': { label: 'Favoritos', section: 'Tienda online' },
      '/store/checkout': { label: 'Checkout', section: 'Tienda online' },
      '/store/shipping': { label: 'Envíos', section: 'Tienda online' },
      '/store/contact': { label: 'Contacto', section: 'Tienda online' },
      '/store/warranty': { label: 'Garantía y devoluciones', section: 'Tienda online' },
      '/store/account/sign-in': { label: 'Acceso cliente', section: 'Cuenta cliente' },
      '/store/account/register': { label: 'Crear cuenta', section: 'Cuenta cliente' },
      '/user/profile': { label: 'Perfil', section: 'Usuario' },
      '/user/account-settings': { label: 'Configuración', section: 'Usuario' },
      '/authentication/sign-in': { label: 'Acceso interno', section: 'Acceso' },
      '/authentication/password-reset': { label: 'Recuperar contraseña', section: 'Acceso' },
      '/authentication/two-factor': { label: 'Verificación 2FA', section: 'Acceso' },
    },
  },
  {
    id: 'volketas',
    name: 'Volketas',
    description: 'Base operativa compacta para coordinación de servicios, despacho, activos, clientes y seguimiento.',
    themeColorId: 'volketas',
    viewPaths: [
      '/applications/management/dashboard',
      '/applications/management/dispatch',
      '/applications/management/orders',
      '/applications/management/service-order',
      '/applications/calendar',
      '/maps',
      '/applications/management/alerts',
      '/applications/management/customers',
      '/applications/management/asset',
      '/user/profile',
      '/user/account-settings',
      '/authentication/sign-in',
      '/authentication/password-reset',
      '/authentication/two-factor',
    ],
    viewPresentation: {
      '/applications/management/dashboard': { label: 'Dashboard', section: 'General' },
      '/applications/management/dispatch': { label: 'Despacho', section: 'Operaciones' },
      '/applications/management/orders': { label: 'Servicios', section: 'Operaciones' },
      '/applications/management/service-order': { label: 'Orden de servicio', section: 'Operaciones' },
      '/applications/calendar': { label: 'Calendario', section: 'Operaciones' },
      '/maps': { label: 'Mapa', section: 'Operaciones' },
      '/applications/management/alerts': { label: 'Alertas', section: 'Operaciones' },
      '/applications/management/customers': { label: 'Clientes', section: 'Relaciones' },
      '/applications/management/asset': { label: 'Activos', section: 'Activos' },
      '/user/profile': { label: 'Perfil', section: 'Usuario' },
      '/user/account-settings': { label: 'Configuración', section: 'Usuario' },
      '/authentication/sign-in': { label: 'Iniciar sesión', section: 'Acceso' },
      '/authentication/password-reset': { label: 'Recuperar contraseña', section: 'Acceso' },
      '/authentication/two-factor': { label: 'Verificación 2FA', section: 'Acceso' },
    },
  }
];

export function getProjectPreset(presetId: string | null) {
  return projectPresets.find((preset) => preset.id === presetId);
}

export function getPresetViewPresentation(presetId: string | null, path: string) {
  return getProjectPreset(presetId)?.viewPresentation?.[path];
}
