import type { ProjectPresetDefinition } from '@/composer/project.types';

export const projectPresets: readonly ProjectPresetDefinition[] = [
  {
    id: 'blank',
    name: 'Aplicación vacía',
    description: 'Empieza sin vistas seleccionadas y construye la navegación desde cero.',
    viewPaths: [],
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce',
    description: 'Base comercial con dashboard, catálogo, tienda, clientes, facturas y seguimiento.',
    viewPaths: [
      '/dashboard',
      '/applications/ecommerce/products',
      '/applications/ecommerce/shop',
      '/applications/ecommerce/product',
      '/applications/ecommerce/editor',
      '/applications/contacts',
      '/applications/invoices/list',
      '/applications/invoices/preview',
      '/applications/tasks',
      '/charts',
    ],
  },
  {
    id: 'crm',
    name: 'CRM',
    description: 'Base orientada a relación con clientes, comunicación, tareas y seguimiento visual.',
    viewPaths: [
      '/dashboard',
      '/applications/contacts',
      '/applications/chat',
      '/applications/mailbox',
      '/applications/notes',
      '/applications/kanban',
      '/applications/tasks',
      '/charts',
      '/user/profile',
    ],
  },
  {
    id: 'admin-erp',
    name: 'ERP administrativo',
    description: 'Base administrativa con facturación, seguimiento, métricas y configuración.',
    viewPaths: [
      '/dashboard',
      '/applications/contacts',
      '/applications/invoices/list',
      '/applications/invoices/editor',
      '/applications/invoices/preview',
      '/applications/notes',
      '/applications/tasks',
      '/charts',
      '/widgets',
      '/user/account-settings',
    ],
  },
  {
    id: 'content',
    name: 'Contenido / Blog',
    description: 'Base editorial con listado, cuadrícula, artículo, editor y utilidades de publicación.',
    viewPaths: [
      '/dashboard',
      '/applications/blog/list',
      '/applications/blog/grid',
      '/applications/blog/post',
      '/applications/blog/editor',
      '/applications/notes',
      '/applications/tasks',
    ],
  },
  {
    id: 'fixphone',
    name: 'FixPhone',
    description: 'MVP web para operación, inventario de celulares/repuestos y tienda online, usando solo superficies reales reutilizables.',
    themeColorId: 'blue',
    viewPaths: [
      '/apps/inventory/dashboard',
      '/apps/inventory/devices',
      '/apps/inventory/devices/new',
      '/apps/inventory/devices/evaluation',
      '/applications/management/inventory',
      '/applications/management/customers',
      '/applications/management/orders',
      '/admin/master-data/brands',
      '/admin/master-data/device-models',
      '/admin/master-data/categories',
      '/admin/master-data/colors',
      '/admin/master-data/storage-capacities',
      '/admin/master-data/ram-capacities',
      '/admin/master-data/conditions',
      '/admin/master-data/spare-part-types',
      '/store',
      '/store/products',
      '/store/spare-parts',
      '/store/used-phones',
      '/store/brands',
      '/store/products/iphone-13-display-oled',
      '/store/cart',
      '/store/favorites',
      '/store/checkout',
      '/store/shipping',
      '/store/contact',
      '/store/warranty',
      '/store/account/sign-in',
      '/store/account/register',
      '/user/profile',
      '/user/account-settings',
      '/authentication/sign-in',
      '/authentication/password-reset',
      '/authentication/two-factor',
    ],
  },
  {
    id: 'volketas',
    name: 'Volketas',
    description: 'Plantilla visible para gestión de volquetas con navegación operativa y vistas activas sin sustitutos falsos.',
    themeColorId: 'volketas',
    viewPaths: [
      '/applications/management/dashboard',
      '/applications/management/dispatch',
      '/applications/management/orders',
      '/applications/calendar',
      '/maps',
      '/applications/management/customers',
      '/user/profile',
      '/user/account-settings',
      '/authentication/sign-in',
      '/authentication/password-reset',
      '/authentication/two-factor',
    ],
  },
];

export function getProjectPreset(presetId: string | null) {
  return projectPresets.find((preset) => preset.id === presetId);
}
