import { useState } from 'react';
import { AppIcon, type AppIconName } from '@/components/AppIcon';
import { SurfaceCard } from '@/components/layout/SurfaceCard';
import { TextField } from '@/components/forms/TextField';
import { PageShell } from '@/shell/PageShell';

export type ElementShowcaseKind = 'alerts' | 'avatars' | 'badges' | 'breadcrumbs' | 'buttons' | 'colors' | 'dropdowns' | 'info-boxes' | 'loaders' | 'pagination' | 'popovers' | 'progress' | 'search' | 'tooltips' | 'tree-view' | 'typography';

const palette = [
  ['Primario', 'var(--theme-primary)'],
  ['Superficie suave', 'var(--theme-primary-soft)'],
  ['Éxito', '#16803a'],
  ['Aviso', '#b7791f'],
  ['Peligro', '#c62828'],
];

function ElementDemo({ kind }: { kind: ElementShowcaseKind }) {
  const [open, setOpen] = useState(false);
  const [page, setPage] = useState(1);
  if (kind === 'alerts') return <div className="space-y-2">{[['Información', 'El cambio está listo para revisión.', 'blue'], ['Éxito', 'La operación se completó correctamente.', 'green'], ['Aviso', 'Hay una acción pendiente.', 'amber'], ['Error', 'No fue posible completar la operación.', 'red']].map(([title, text, tone]) => <div key={title} className={`rounded-md border p-3 text-[11px] ${tone === 'green' ? 'border-emerald-100 bg-emerald-50 text-emerald-800' : tone === 'amber' ? 'border-amber-100 bg-amber-50 text-amber-800' : tone === 'red' ? 'border-red-100 bg-red-50 text-red-800' : 'border-blue-100 bg-blue-50 text-blue-800'}`}><strong>{title}</strong><span className="ml-2">{text}</span></div>)}</div>;
  if (kind === 'avatars') return <div className="flex items-center gap-2">{['LH', 'AM', 'CV', 'JR'].map((initials) => <div key={initials} className="grid size-10 place-items-center rounded-full bg-[var(--theme-primary-soft)] text-[11px] font-semibold text-[var(--theme-primary)] ring-2 ring-white">{initials}</div>)}</div>;
  if (kind === 'badges') return <div className="flex flex-wrap gap-2">{['Activo', 'En revisión', 'Borrador', 'Archivado'].map((label, index) => <span key={label} className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${index === 0 ? 'bg-emerald-50 text-emerald-700' : index === 1 ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'}`}>{label}</span>)}</div>;
  if (kind === 'breadcrumbs') return <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-[11px] text-slate-500"><span>Inicio</span><span>/</span><span>Componentes</span><span>/</span><span className="font-semibold text-slate-800">Elementos</span></nav>;
  if (kind === 'buttons') return <div className="flex flex-wrap gap-2"><button className="rounded-md bg-[var(--theme-primary)] px-3 py-2 text-[11px] font-semibold text-white" type="button">Primario</button><button className="rounded-md border border-slate-200 px-3 py-2 text-[11px] font-semibold text-slate-700" type="button">Secundario</button><button className="rounded-md border border-red-200 px-3 py-2 text-[11px] font-semibold text-red-700" type="button">Peligro</button><button className="rounded-md bg-slate-100 px-3 py-2 text-[11px] font-semibold text-slate-400" disabled type="button">Deshabilitado</button></div>;
  if (kind === 'colors') return <div className="grid gap-2 sm:grid-cols-5">{palette.map(([label, color]) => <div key={label}><div className="h-16 rounded-md border border-slate-100" style={{ backgroundColor: color }} /><p className="mt-2 text-[10px] font-semibold text-slate-700">{label}</p><p className="mt-1 text-[10px] text-slate-400">{color}</p></div>)}</div>;
  if (kind === 'dropdowns') return <div className="relative inline-block"><button className="flex items-center gap-2 rounded-md border border-slate-200 px-3 py-2 text-[11px] font-semibold text-slate-700" onClick={() => setOpen(!open)} type="button">Acciones <AppIcon className="size-3" name="chevron-down" /></button>{open ? <div className="absolute left-0 top-11 z-10 w-40 rounded-md border border-slate-200 bg-white p-1 shadow-lg"><button className="w-full rounded px-2 py-2 text-left text-[11px] text-slate-700 hover:bg-slate-50" type="button">Editar</button><button className="w-full rounded px-2 py-2 text-left text-[11px] text-slate-700 hover:bg-slate-50" type="button">Duplicar</button></div> : null}</div>;
  if (kind === 'info-boxes') return <div className="grid gap-2 sm:grid-cols-3">{[['Contexto', 'La información acompaña al control.', 'book'], ['Estado', 'El usuario puede entender el resultado.', 'dashboard'], ['Ayuda', 'El siguiente paso queda explícito.', 'help']].map(([title, text, icon]) => <div key={title} className="rounded-md border border-slate-100 bg-slate-50/70 p-3"><AppIcon className="size-4 text-[var(--theme-primary)]" name={icon as AppIconName} /><p className="mt-2 text-[11px] font-semibold text-slate-800">{title}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{text}</p></div>)}</div>;
  if (kind === 'loaders') return <div className="flex items-center gap-6"><div className="size-8 animate-spin rounded-full border-2 border-slate-200 border-t-[var(--theme-primary)]" /><div className="flex gap-1"><span className="size-2 animate-pulse rounded-full bg-[var(--theme-primary)]" /><span className="size-2 animate-pulse rounded-full bg-[var(--theme-primary)] [animation-delay:150ms]" /><span className="size-2 animate-pulse rounded-full bg-[var(--theme-primary)] [animation-delay:300ms]" /></div><span className="text-[11px] text-slate-500">Cargando contenido…</span></div>;
  if (kind === 'pagination') return <div className="flex items-center gap-1"><button className="rounded border border-slate-200 px-2 py-1 text-[11px] text-slate-500" onClick={() => setPage(Math.max(1, page - 1))} type="button">Anterior</button>{[1, 2, 3].map((item) => <button key={item} className={`size-7 rounded text-[11px] font-semibold ${page === item ? 'bg-[var(--theme-primary)] text-white' : 'border border-slate-200 text-slate-600'}`} onClick={() => setPage(item)} type="button">{item}</button>)}<button className="rounded border border-slate-200 px-2 py-1 text-[11px] text-slate-500" onClick={() => setPage(Math.min(3, page + 1))} type="button">Siguiente</button></div>;
  if (kind === 'popovers') return <div className="text-center"><button className="rounded-md border border-slate-200 px-3 py-2 text-[11px] font-semibold text-slate-700" onClick={() => setOpen(!open)} type="button">Mostrar popover</button>{open ? <div className="mx-auto mt-3 max-w-xs rounded-md border border-slate-200 bg-white p-3 text-left shadow-sm"><p className="text-[11px] font-semibold text-slate-800">Detalle contextual</p><p className="mt-1 text-[10px] leading-4 text-slate-500">Este contenido aparece cerca del control que lo activa.</p></div> : null}</div>;
  if (kind === 'progress') return <div className="space-y-3">{[['Carga del proyecto', 72], ['Revisión visual', 44], ['Publicación', 18]].map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-[10px] font-semibold text-slate-600"><span>{label}</span><span>{value}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-[var(--theme-primary)]" style={{ width: value + '%' }} /></div></div>)}</div>;
  if (kind === 'search') return <TextField label="Buscar" placeholder="Escribe para filtrar…" />;
  if (kind === 'tooltips') return <div className="flex gap-3"><button className="rounded-md border border-slate-200 px-3 py-2 text-[11px] text-slate-700" title="Información adicional" type="button">Pasa el cursor</button><button className="rounded-md border border-slate-200 px-3 py-2 text-[11px] text-slate-700" title="Acción secundaria" type="button">Otro tooltip</button></div>;
  if (kind === 'tree-view') return <div className="space-y-2 text-[11px] text-slate-700"><details open><summary className="cursor-pointer font-semibold">WebBlueprint</summary><div className="ml-4 mt-2 space-y-2"><details open><summary className="cursor-pointer">src</summary><p className="ml-4 mt-1 text-slate-500">components/ · features/ · shell/</p></details><p>docs/</p></div></details></div>;
  return <div className="space-y-3"><h1 className="text-2xl font-semibold tracking-tight text-slate-900">Título principal</h1><h2 className="text-lg font-semibold text-slate-800">Subtítulo de sección</h2><p className="text-sm leading-6 text-slate-600">Texto de lectura normal con una longitud cómoda y una jerarquía clara.</p><code className="block rounded bg-slate-100 p-2 text-[11px] text-slate-700">font-semibold · text-slate-700</code></div>;
}

export function ElementShowcasePage({ kind, title, description }: { kind: ElementShowcaseKind; title: string; description: string }) {
  return <PageShell breadcrumbs={[{ label: 'Elementos' }, { label: title }]} description={description} title={title}><SurfaceCard><div className="flex items-start gap-3"><div className="grid size-9 place-items-center rounded-md bg-[var(--theme-primary-soft)] text-[var(--theme-primary)]"><AppIcon className="size-[18px]" name="layers" /></div><div><h2 className="text-[13px] font-semibold text-slate-900">Ejemplo reutilizable</h2><p className="mt-1 text-[11px] leading-4 text-slate-500">La demostración usa tokens y estados compartidos del Blueprint.</p></div></div><div className="mt-5"><ElementDemo kind={kind} /></div></SurfaceCard></PageShell>;
}
